### ISSUE TITLE
Having an issue where text isn't visible

### ISSUE THREAD

**Issue by witchka** [TEParsons/LCARS#2]
Hi! Love that you've made this, thank you so much. But I'm having a bit of a funny issue where I can't see what I'm typing or the text after typing unless it's a header. I'm including a screenshot of the same file with lcars vs another theme, I reinstalled it to make sure I hadn't messed it up somehow but it made no difference. Any advice would be great, thank you! 

<img width="957" alt="Screenshot 2023-11-29 at 4 44 10 pm" src="https://github.com/TEParsons/LCARS/assets/17267764/2c6a94c3-3e7f-4bd6-9d37-7abf4ff89608">
<img width="979" alt="Screenshot 2023-11-29 at 4 45 11 pm" src="https://github.com/TEParsons/LCARS/assets/17267764/040f060a-3c72-4fe5-b063-9f7c7bd7bbe5">

**Comment by TEParsons** [comment]
That's very strange... If you select it, can you see the selection? I'd guess it's that the text colour is being set to black, aka the same colour as the background.

Regular text should just inherit the `:root` colour, which is that pale yellow, same as the headings. I'd guess there's something that's overriding it, maybe from Typora or even from your operating system defaults.

**Comment by witchka** [comment]
Sorry, I thought this would notify me but it didn't but no- highlighting does nothing to allow me to see text. I don't have any problems with other typora themes so I'm not sure what on my end could be doing it.
<img width="1005" alt="Screenshot 2023-12-16 at 9 32 13 am" src="https://github.com/TEParsons/LCARS/assets/17267764/51d84ef5-9fde-41c4-b11d-bfa80bf337cd">

**Comment by TEParsons** [comment]
Thanks for trying that! So it looks like my guess was wrong, black text would show up when selected. Those red and blue lines I'm guessing are places where text would be underlined, so the text seems to be there, just invisible. The fact that headings are visible is probably they key so I'll try to figure out what I'm doing with headings that I'm not doing with paragraph text.

What OS are you on? I built this on Windows but have access to a Mac (albeit only when I'm at work, which I won't be until the new year) so if it's Mac specific I may be able to recreate the bug, which will make it a lot easier to fix.

**Comment by witchka** [comment]
I'm on a mac on Sonoma 14.1.2 and the newest typora. Again, really sorry! Christmas ate me.

**Comment by TEParsons** [comment]
No worries, 2 weeks isn't even that bad for response times on GitHub :')

I'll bet it's a Mac thing then, will give it a go on my office Mac when I'm next in :)

**Comment by TEParsons** [comment]
Think I've got it! Seems that z-index works slightly different on Windows vs Mac, and on Mac if I set the z-index of paragraph elements to -1 then they appear behind the black background... I've fixed it now, will do a new release once I've tested to make sure it doesn't break anything on Windows, but in the meantime you can just download (or copy and paste) from [here](https://github.com/TEParsons/LCARS/blob/main/typora/lcars.css) and you should be good to go :)

**Comment by witchka** [comment]
Ahh! Thank you that looks great.
