### ISSUE TITLE
Dark mode has blinding white sidebar on Mac

### ISSUE THREAD

**Issue by cyanomys** [TEParsons/LCARS#3]
Not sure why, mac is in dark mode. 
<img width="1352" alt="image" src="https://github.com/TEParsons/LCARS/assets/63557988/92f6b8eb-46b8-4b0b-a9a9-90fad2540430">

**Comment by TEParsons** [comment]
Good catch, thanks! Fixed this in the main branch, so you can download [here](https://github.com/TEParsons/LCARS/blob/main/typora/lcars.css) for an immediate fix, or wait for the next release (found a few other bugs while fixing this so will do a release once I've got them all ironed out)
